import localFont from "next/font/local";
import "./globals.css";

import { StrictMode } from 'react'
import { Analytics } from "@vercel/analytics/react"

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Choice",
  description: "Generated by create next app",
};
// app/layout.tsx
export default function RootLayout({
  children,
}) {
  return (
    
    <StrictMode>
    <html lang="en">
      <head>
      <script type="module"> import mermaid from https://cdn.jsdelivr.net/npm/mermaid@11.4.0/+esm </script>
      </head>
      <body suppressHydrationWarning={true} className="antialiased">
        {children}
      </body>
      <Analytics/>
    </html>
    </StrictMode>
  );
}
// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//     </StrictMode>
//   );
// }
